import{a as d,S as u,i as n}from"./assets/vendor-CaRFiM55.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="51737021-87f818cc1ae3d02e4bfd7c05a",m="https://pixabay.com/api/";function h(s){const o={key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return d.get(m,{params:o}).then(t=>t.data)}const l=document.querySelector(".gallery"),i=document.querySelector(".loader");i.classList.add("is-hidden");const p=new u(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const o=s.map(t=>`
    <li>
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <p> ${t.likes}  ${t.views}  ${t.comments}  ${t.downloads}</p>
    </li>
  `).join("");l.insertAdjacentHTML("beforeend",o),p.refresh()}function g(){l.innerHTML=""}function L(){i.classList.remove("is-hidden")}function b(){i.classList.add("is-hidden")}const S=document.querySelector(".form");S.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(!o){n.error({title:"Ошибка",message:"Введите поисковый запрос"});return}g(),L(),h(o).then(t=>{t.hits.length===0?n.info({title:"Нет результатов",message:"Sorry, there are no images matching your search query. Please try again!"}):y(t.hits)}).catch(()=>{n.error({title:"Ошибка",message:"Что-то пошло не так. Попробуйте снова."})}).finally(()=>{b()})});
//# sourceMappingURL=index.js.map
