import{a as u,S as f,i as a}from"./assets/vendor-CaRFiM55.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d="51737021-87f818cc1ae3d02e4bfd7c05a",m="https://pixabay.com/api/";function p(s){const o={key:d,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return u.get(m,{params:o}).then(t=>t.data)}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),y=new f(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const o=s.map(t=>`
    <li>
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <p>❤️ ${t.likes} 👁 ${t.views} 💬 ${t.comments} ⬇️ ${t.downloads}</p>
    </li>
  `).join("");c.insertAdjacentHTML("beforeend",o),y.refresh()}function g(){c.innerHTML=""}function L(){l.classList.remove("is-hidden")}function b(){l.classList.add("is-hidden")}const S=document.querySelector(".form");S.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements["search-text"].value.trim();if(!o){a.error({title:"Ошибка",message:"Введите поисковый запрос"});return}g(),L(),p(o).then(t=>{t.hits.length===0?a.info({title:"Нет результатов",message:"Sorry, there are no images matching your search query. Please try again!"}):h(t.hits)}).catch(()=>{a.error({title:"Ошибка",message:"Что-то пошло не так. Попробуйте снова."})}).finally(()=>{b()})});
//# sourceMappingURL=index.js.map
